# 数据库连接信息
spring:
  datasource:
    username: root
    password: niit1234
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver